<!DOCTYPE html>
<html lang="en">
<head>
    <title>Practice file For OOPS Concepts</title>
</head>
<body>
    <!-- 1. Constructor -->

    <script>
      //By Akshay saini
      // const p = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Promise Resolved Value")
      //   }, 5000)
      // })

      // Note - jaise hi await dekhne ko milta hai js engine uss async function ko suspen kar deta hai or usse exexution context se remove kar deta hai 
      // or jaise hi vo promise resolve ho jata hai vo again uss async function ko execution context push kar deta hai 
      // or vo vhi se execute karne lgata hai jha se vo pop out hua tha 

      // 1.
      // Using Promises 
      // async function getData(){
      //   p.then((res) => console.log(res));
      //   console.log("Namaste Javascript");
      // }
      // getData() 
      // output - Namaste javascript 
      //          Promise Resolved value 

      // 2.
      // Using Async_await 
      // async function handlePromise(){
      //   const val = await p;
      //   console.log(val);
      //   console.log("Namaste Javascript");
      // }
      // handlePromise();
      // // ye pura ek sath 5sec. baad execute hoga
      // // the code was waiting at line number 27 for 5 Sec then execute altogether
      // // JS engine was waiting for promise to resolved - But internally it's not happening
      // // output - Promise Resolved value
      // //          Namaste Javascript

      // 3.
      // async function handlePromise() {
      //   console.log("Hello World");

      //   // Js Engine was waiting for promise to resolved - But internally it's not happening
      //   const val = await p;
      //   console.log(val);
      //   console.log("Namaste Javascript");
      // }
      // handlePromise();
      // output - Hello world
      //          Promise Resolved value
      //          Namaste Javascript
      // Hello World run first then after 5Sec. next two line run

      // // 4. What will happen in case of two promises 
      // const p1 = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Promise Resolved Value")
      //   }, 5000)
      // })

      // const p2 = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Promise-2 Resolved Value")
      //   }, 10000)
      // }) 
      // async function handlePromise() {
      //   console.log("Hello World");

      //   // Js Engine was waiting for promise to resolved - But internally it's not happening
      //   const val = await p1;
      //   console.log(val);
      //   console.log("Namaste Javascript");

      //   const val2 = await p2;
      //   console.log(val2);
      //   console.log("Namaste Javascript");
      // }
      // handlePromise();
      // // output - Hello world
      // // pehle 5 Sec vala promise resolved hoga than 10 sec vala promise resolve hoga
      // //          Promise Resolved value
      // //          Namaste Javascript
      // // After 10 sec.
      // //          Promise-2 Resolved value
      // //          Namaste Javascript

      // 5. What will happen in case of two promises 
      // const p1 = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Promise Resolved Value")
      //   }, 10000)
      // })

      // const p2 = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve("Promise-2 Resolved Value")
      //   }, 5000)
      // }) 
      // async function handlePromise() {
      //   console.log("Hello World");

      //   // Js Engine was waiting for promise to resolved - But internally it's not happening
      //   const val = await p1;
      //   console.log(val);
      //   console.log("Namaste Javascript");

      //   const val2 = await p2;
      //   console.log(val2);
      //   console.log("Namaste Javascript");
      // }
      // handlePromise();
      // output - Hello world
      // dono 10 Sec baad resolve honge
      //          Promise Resolved value
      //          Namaste Javascript
      //          Promise-2 Resolved value
      //          Namaste Javascript

      // Note - JS engine just appear to waiting, it not consuming memory or occupaying call stack
      // sabse pehle hamara hanflePromise function call stack me aayega and then 
      // it will start executinf line by line then 
      // it will print hello world and then 
      // as it see await this handlePromise execution suspent and this will move outof call stack
      // and it won't block the call stack  
      // and then it will wait till than it p1 won't resolved than only it will move ahead
      // as promise resolve this handlePromise function come again inside the call stack
      // and it again start executing but this time it will start executing where it actually left.

/// --------------------------------------------------------------------------------------------------------------
      
      // Example with class 

      // class Ecom{
      //   constructor(){
      //     this.cart = [];
      //     this.order = null;
      //     this.walletBalance = 100;
      //   }

      //   addItem(item){
      //     this.cart.push(item);
      //     return Promise.resolve(`Added ${item.name} to the cart`)
      //   }

      //   createOrder(){
      //     if(this.cart.length === 0){
      //       return Promise.reject("Cart is empty, Please add item into cart")
      //     }

      //     this.order = {
      //       items: this.cart,
      //       total: this.calculateTotal()
      //     }

      //     return Promise.resolve("order created");
      //   }

      //   calculateTotal(){
      //     return this.cart.reduce((total, item) => item.price, 0)
      //   }

      //   proceedToPayment() {
      //     if (!this.order) {
      //       return Promise.reject("No order to proceed with payment.");
      //     }

      //     if (this.order.total > this.walletBalance) {
      //       return Promise.reject("Insufficient wallet balance.");
      //     }

      //     this.walletBalance -= this.order.total;

      //     return Promise.resolve("Payment successful");
      //   }

      //   orderSummery(){
      //     if(!this.order){
      //       return Promise.reject("No order to display")
      //     }

      //     return Promise.resolve(this.order)
      //   }

      //   updateWallet(amount){
      //     this.walletBalance += amount;
      //     return Promise.resolve(`Wallet Updated, current Balance ${this.walletBalance}`)
      //   }
      // }

      // const cart = new Ecom();

      // cart.addItem({name: "kurta", price: 10})
      // .then((res) => {
      //   console.log(res);
      //   return cart.createOrder();
      // })
      // .then((res) => {
      //   console.log(res);
      //   return cart.proceedToPayment()
      // })
      // .then((res) => {
      //   console.log(res);
      //   return cart.orderSummery();
      // })
      // .then((res) => {
      //   console.log(res);
      //   return cart.updateWallet(1000);
      // })
      // .then((res) => {
      //   console.log(res);
      // })

      // const p = new Promise((resolve, reject) => {
      //   if(!true){
      //     reject(new Error("invalid item found"))
      //   }
      //   resolve("successful")
      // })

      // p.then((res) => {
      //   console.log(res);
      // })


      // firstly run creation phase than exexution phase works
      // that is why we are getting an 10.
      // function a(){
      //   var b = 10;
      //   c();
      //   function c(){
      //     console.log(b);
      //   }
      // }
      // a()

      // //Block scope

      // {
      //   var a = 10;
      //   let b = 20;
      //   const c = 30;
      // }

      function x(){
        for(var i = 1; i < 5; i++){
          function y(i){
            setTimeout(() => {
              console.log(i);
            }, i*1000)
          }
          y(i)
        }
        console.log("namaste js");
      }
      x()
    </script>
</body>
</html>
